# Database
database:
  # Logging SQL queries
  echo: True
  # Connection pool size
  pool_size: 2 # The number of permanent connections in the pool
  max_overflow: 5 # Maximum number of temporary connections over pool_size
  # Checking connections
  pre_ping: False # Checks if the connection is live before using
  # Re-creating connections
  pool_recycle: 3600 # 1 hour. Forcibly recreates connections every N seconds
  # Pool class
  pool_class:
    "NullPool" # "QueuePool" - shared connection pool
    # "NullPool" - without a pool (new connection every time)
    # Session Settings
  # The objects remain available after the commit.
  expire_on_commit: False # The objects remain available after the commit.
  # Explicit transaction management
  autocommit: False
  # Explicit flush control
  autoflush: False
  # Support for SQLAlchemy 2.x style
  future: True
  protocol: postgresql+asyncpg

log:
  logs_dir: "./logs"
  file_system: "system.log"
  file_user: "user.log"
  max_bytes: 10485760
  backup_count: 5
  encoding: "utf-8"
  system_format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  user_format: "%(asctime)s - %(message)s"
  file_level: "INFO"
  console_level: "DEBUG"
  root_level: "DEBUG"
  werkzeug_level: "INFO"