# Database
database:
  # Logging SQL queries
  echo: True
  # Connection pool size
  pool_size: 2 # The number of permanent connections in the pool
  max_overflow: 5 # Maximum number of temporary connections over pool_size
  # Checking connections
  pre_ping: False # Checks if the connection is live before using
  # Re-creating connections
  pool_recycle: 3600 # 1 hour. Forcibly recreates connections every N seconds
  # Pool class
  pool_class:
    "NullPool" # "QueuePool" - shared connection pool
    # "NullPool" - without a pool (new connection every time)
    # Session Settings
  # The objects remain available after the commit.
  expire_on_commit: False # The objects remain available after the commit.
  # Explicit transaction management
  autocommit: False
  # Explicit flush control
  autoflush: False
  # Support for SQLAlchemy 2.x style
  future: True
  async_protocol: postgresql+asyncpg
  sync_protocol: postgresql
  alembic:
    ini_path: "f_alembic/alembic.ini"

log:
  # A directory for storing log files (relative or absolute path).
  # Will be created automatically at the first launch if it does not exist.
  logs_dir: "./logs"
  # Application operation events, exceptions, starts/stops are written here.
  file_system: "system.log"
  # It can contain business events: notification created, sent, validation error.
  file_user: "user.log"
  # The maximum size of the log file in bytes (10 MB).
  # If exceeded, rotation occurs (a new file is created, the old one is renamed).
  max_bytes: 10485760
  # The number of log files stored during rotation.
  backup_count: 5
  # Encoding of text in log files.
  encoding: "utf-8"
  # The message format for the system log.
  # %(asctime)s - time
  # %(name)s - name of the logger
  # %(levelname)s - level
  # %(message)s - text.
  system_format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  # Message format for the user log.
  user_format: "%(asctime)s - %(levelname)s - %(message)s"
  # The logging level for writing to files (DEBUG, INFO, WARNING, ERROR, CRITICAL).
  # Messages below this level are not included in the files..
  file_level: "INFO"
  # The logging level for output to the console (stderr/stdout).
  console_level: "DEBUG"
  # The root logging level for all loggers.
  root_level: "DEBUG"
  # Logging level for the Werkzeug library (Flask is used for HTTP requests).
  werkzeug_level: "ERROR"